### ISSUE TITLE
Image not found!

### ISSUE THREAD

**Issue by ninnube** [webp-sh/webp_server_go#292] opened 2023-11-13 08:50 UTC
I'm using this config.json with remote backend url.
```{
  "HOST": "127.0.0.1",
  "PORT": "3333",
  "QUALITY": "80",
  "IMG_PATH": "https://my-domain.com",
  "EXHAUST_PATH": "",
  "ALLOWED_TYPES": ["jpg","png","jpeg","bmp","gif","svg","heic"],
}
```
Webp server cannot get images from my original remote backend site

**Logs**
```time="2023-11-13 08:48:29" level=warning msg="Image not found!" func="[150:webp_server_go/handler.Convert]"
 - [2023-11-13 08:48:29] GET /wp-content/uploads/2023/11/123.jpeg 404  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
time="2023-11-13 08:48:29" level=warning msg="File extension not allowed! robots.txt" func="[42:webp_server_go/handler.Convert]"
```

**Comment by n0vad3v** [comment] 2023-11-13 12:07
Cannot reproduce your error, could you please provide:
1. The version of WebP Server Go you're using
2. The complete real config of `config.json` (Contains your real IMG_PATH instead of `"https://my-domain.com",`
3. How you are running WebP Server Go (Binary/Docker ,etc)

**Comment by n0vad3v** [comment] 2024-03-15 13:17
Closing this issue now as we haven't received any response from the creator for an extended period of time.

**Closed by n0vad3v** 2024-03-15 13:17 UTC
Labels: invalid
